version: "3"

services:
    nginx:
        image: nginx:latest
        ports: 
            - "80:80"
            - "443:443"
        restart: unless-stopped
        volumes: 
            - "./nginx.conf:/etc/nginx/nginx.conf"
            - "./data/certbot/conf:/etc/letsencrypt"
            - "./data/certbot/www:/var/www/certbot"
        command : "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    back:
        depends_on:
            - nginx
        image: cheertogether_be:latest
        ports:
            - "8081:8081"
        restart: always
    front:
        depends_on:
            - nginx
        image: cheertogether_fe:latest
        restart: always
    nginx-media-server:
        depends_on:
            - nginx
        image: woonizzooni/nginx-media-server:latest
        ports:
            - "1935:1935"
            - "8080:8080"
        restart: always
        volumes:
            - "./nginx_rtmp.conf:/etc/nginx/nginx.conf"

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - "./data/certbot/conf:/etc/letsencrypt"
            - "./data/certbot/www:/var/www/certbot"
        depends_on:
            - nginx
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
